### ISSUE TITLE
How about the results without jointly training on COCO

### ISSUE THREAD

**Issue by fujihuang** [dvornikita/blitznet#22]
Hi, would you like to share the results which do not adopt jointly training on coco dataset.
Best

**Comment by dvornikita** [comment]
Hi, I don't understand what result you mean. Can you clarify?

**Comment by fujihuang** [comment]
Thanks for your reply. I mean the coco 2015 test-dev results of the model just use detection annotations to train, without using any segmentation annotations.
Best

**Comment by dvornikita** [comment]
In table 5 of the original paper, we report gains in accuracy with joint training on COCO minival2014. Since the performance of the model trained on a single task only is not the purpose of our work we don't report it on the test set. 
However, if you are interested, you can obtain these results using the code in this repo.
Best

**Comment by fujihuang** [comment]
oh, yes, thanks for your reply again.
Best,
