### ISSUE TITLE
How to best deal with input images with fixed aspect ratio different from 1 (and not resizing)

### ISSUE THREAD

**Issue by revilokeb** [dvornikita/blitznet#23]
I understand that Blitznet resizes images to 512x512 or 300x300 in its current implementation. This is being done during training in training.py in function extract_batch in function data_augmentation (https://github.com/dvornikita/blitznet/blob/8f413feb37d6be7bc9df07f045062451a07a5dde/utils_tf.py#L168).

However if I would like to keep the aspect ratio of my dataset (all images are hxw, e.g. 256x512) that line can be removed. However then there is a mismatch between the number of anchor boxes and the net output (i.e. in function detection_loss size of tensors location and pos_mask do no longer match).

I have healed that kind of ad hoc by removing the last layer with fm_sizes=1 (https://github.com/dvornikita/blitznet/blob/8f413feb37d6be7bc9df07f045062451a07a5dde/config.py#L179) and doubling num_priors (https://github.com/dvornikita/blitznet/blob/8f413feb37d6be7bc9df07f045062451a07a5dde/resnet.py#L162, for the case of 256x512 input) to effectively get the same output size of the multibox head. This seems to work. I was wondering if there is some way to deal with that situation that is conceptually sounder?

**Comment by dvornikita** [comment]
The right way to do it is to change the parameters of the initial tiling in the file boxer.py. The class PriorBoxGrid generates the tiling for a square area. If you make the tiling of an area with aspect ratio 1/2 you will have the right number of boxes that match the outputs of the convolutions.

Also, you may not want to do that at all because during the data augmentation parts of an image are randomly cropped and rescaled to a square. Since there are no constraints on cropping aspect ratio, the final aspect ratio of the patch is different from the original image. 
What I'm saying is that even if you change the aspect ratio of the full pipeline you will still train on warped patches. If you train without random crops, the performance if likely to drop for the reason of lacking data augmentation.

**Comment by dvornikita** [comment]
No problems.

**Comment by juliagviu** [comment]
Could you please @revilokeb explain deeper how you adjusted the tiling? I am working with 512x1024 images and need to solve the same issue, but I am not sure how to make initial tilings of ratio 1/2. Thanks very much!
