### ISSUE TITLE
VOC dataset preparation difficulties

### ISSUE THREAD

**Issue by revilokeb** [dvornikita/blitznet#3]
@dvornikita Many thanks for making this publicly available, very nice results!! My questions relate to current version a0403d3f4e90b0d6d0c617292080ae4a5f4af1e1. 

I have been wondering why in https://github.com/dvornikita/blitznet/blob/master/datasets.py row 210 `segmentation=True`, **I was expecting `segmentation=segmentation`**?

Also, in https://github.com/dvornikita/blitznet/blob/master/voc_loader.py row row 39 
`assert not self.segmentation or self.segmentation and self.year == '12'`
it seems impossible to get a segmentation dataset from VOC2007 (although it should be possible in my understanding), i.e. `python datasets.py` with `create_voc_dataset('07', 'trainval', True)` uncommented is running into this assert. **What is the reason for this assert**?

Last but not least a question on splits_to_sizes in https://github.com/dvornikita/blitznet/blob/master/datasets.py (lines 71-87): 
1. `voc12-train-segmentation: 10582`  - relates to the number of training files in the augmented segmentation dataset, i.e. number of lines in VOCdevkit/VOC2012/ImageSets/SegmentationAug/train.txt. 
2. `voc12-train-segmentation-original: 1464` - corresponds to the number of training files in original VOC2012 segmentation, i.e. VOCdevkit/VOC2012/ImageSets/Segmentation/train.txt
3. `voc12-val-segmentation: 1449` - corresponds to the number of training files in original VOC 2012 segmentation, i.e. VOCdevkit/VOC2012/ImageSets/Segmentation/val.txt

So far so good, **however, I have hard time to confirm numbers for VOC2007**. I am finding that VOCdevkit/VOC2007/ImageSets/Segmentation/train.txt is containing 209 rows, val.txt 213 rows, trainval.txt (not surprisingly) 422 rows and test.txt 210 rows. This is very different from the numbers I am seeing in splits_to_sizes for voc2007. What am I doing wrong?

**Comment by dvornikita** [comment]
Hi,

The reason for this assert is that there are no segmentation annotations for the VOC07 (in fact, there are, but we didn't use them for training at all, treating it as a detection only dataset). If the segmentation flag is off, we still create segmentation masks for images but fill them with zeros. This is done to preserve the structure of the data independent of the dataset. However, you are right that there should be segmentation=segmentation, in line 210 of datasets.py. Thanks for noticing this, I'll push that.

The numbers that you see in splits_to_sizes reflect the sizes of /ImageSets/Main/train.txt rather than /ImageSets/Segmentation/train.txt. If you would like to include the VOC07 segmentation data in the training, you need to delete the assert you mentioned before and modify the function read_segmentation(...) in voc_loader.py to create void segmentation mask if the gt mask wasn't found in the folder (that's what I would do).

Thank you very much for the meaningful feedback. If you have any other questions, contact me.

**Comment by revilokeb** [comment]
@dvornikita thank you for your reply, got it!
