### ISSUE TITLE
Problem about the generated segmentation mask

### ISSUE THREAD

**Issue by tjulyz** [dvornikita/blitznet#31]
Thanks for your kind share!
Because there is no segmentation mask for voc07 dataset, as you said , zeros are padded for these samples as segmentation masks.  What confused me is whether to compute the segmentation loss for these samples or not. As known, '0' represents background in segmentation labels. when I using 
--run_name=BlitzNet300_x4_VOC0712_detseg
--dataset=voc07+12-segmentation
--trunk=resnet50
--x4
--batch_size=32
--optimizer=adam
--detect
--segment
--max_iterations=65000
--lr_decay
40000
50000
for training the model, and validate the trained model on voc12 validation dataset, the detection performance is 83% map, but only 47%mIoU for segmentation. Can you help me?
Thanks!

**Comment by dvornikita** [comment]
Hi @tjulyz, I guess these scripts were not used to train the model in the mixes setting (with gt segmentation masks and without). If I remember correctly, in the file voc_loader.py, in the [line](https://github.com/dvornikita/blitznet/blob/master/voc_loader.py#L104-L104) add 255 to the segmentation.
In the training.py file, where the segmentation loss is defined, the pixels that have a value of gt segmentation higher than the number of categories in the dataset don't contribute to the loss, they are filtered out.
Don't hesitate to come back with the results.
Good luck.

**Comment by Hshihua** [comment]
Thanks for the rely. @dvornikita 
However, you did not add 255 to the zero-valued segmentation in the original source code. Does it mean  we should add by ourselves?
Best,

**Comment by dvornikita** [comment]
Hi @Hshihua, that's correct. Sorry for the inconvenience. Can't modify the code or run the experiment right now. I'll come back soon and check this myself.

**Comment by Hshihua** [comment]
Thanks for your reply. And I can understand.
Maybe the code should be like: segmentation = np.ones([height, width], dtype=np.uint8) * 255

**Comment by Hshihua** [comment]
Thanks~
If I am doing the right thing, and you just need to modify the code by replacing "segmentation = np.zeros([height, width], dtype=np.uint8)" with segmentation = np.ones([height, width], dtype=np.uint8) * 255" in the voc_loader.py.
Best,

**Comment by dvornikita** [comment]
Yes, that's right.

**Comment by tjulyz** [comment]
Thanks a lot! @dvornikita @Hshihua

**Comment by ganeshtata** [comment]
Hi @tjulyz . I am facing the same issue as yours. The detection performance is 83% map, but only 49% mIoU for segmentation. Does the above change improve the training process?

**Comment by dvornikita** [comment]
Hi @ganeshtata. Yes, it does improve the process. I pushed the modification. 
You need to generate the dataset in tf_record format again and run the training.

**Comment by ganeshtata** [comment]
Great @dvornikita . Thank you for the prompt response! Just a few things that I wanted to add - 
*  Could you please add the reasoning behind this change in the comment above the line? The current comment reads that an image of all zeros is generated. But now, we aren't doing that, but instead generating an image with all 255 values. You have mentioned the reasoning behind it as well in this thread. It would be awesome if you could write the same ( In short ) in the comment above the line.

* Also, instead of writing 
`segmentation = np.zeros([height, width], dtype=np.uint8) + 255`
Could we write - 
`segmentation = np.full([height, width], value=255, dtype=np.uint8)`

These are just a few suggestions. Thank you for this project!

**Comment by dvornikita** [comment]
@ganeshtata you can write either of the lines, they do the same thing. 
0 corresponds to the background class and the value of 255 stands for ignoring the pixel in the loss. If we don’t know the true image semantics it’s better to not make updates on it rather than to treat all its content as background and to learn from a wrong signal.
