### ISSUE TITLE
true_number_of_negatives calculation

### ISSUE THREAD

**Issue by MrGemy95** [dvornikita/blitznet#48]
Can you explain the calculation of the true_number_of_negatives ?
`true_number_of_negatives = tf.minimum(3 * number_of_positives,
                                              tf.shape(pos_mask)[1] - number_of_positives)`

**Comment by dvornikita** [comment]
Hi,
Here we just define the number of negatives as the total number of candidates minus the number of positives (the second argument), but require it to be not greater than 3 times the number of positives (the first argument). Most of the time we end up with true_number_of_negatives = 3 * number_of_positives, because the number of all negatives on the image during the training is orders of magnitude greater than the number of positives.

**Comment by MrGemy95** [comment]
yeah but why you require it to be not larger than 3 times the number of positives?! why don't you just keep the actual number of negatives which is the second argument?.

**Comment by dvornikita** [comment]
Because there will be an imbalance between positive and negative samples and the loss signal will be useless for optimizing the desired behavior. This is the reason we sample hard negatives.
To understand that phenomena better I recommend you to read the original "RCNN" papers and the "Focal Loss" paper.

**Comment by MrGemy95** [comment]
i know that you're trying to balance between the positive and negative samples but why you ignore some of the negative samples to make that balance? why don't you use all samples with smaller weights, i mean as mentioned in SSD and Yolov2 and also as mentioned in focal loss paper.
