### ISSUE TITLE
test.py Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,5 12,64]

### ISSUE THREAD

**Issue by fastlater** [dvornikita/blitznet#6]
@dvornikita 
Thank your for share your code. Based on your papers, this code will become very important in this field.

I have been trying to test the code using the models already trained by you for VOC07+12. 
```
$ python test.py --run_name=BlitzNet300_VOC07+12 --dataset=voc07 --split=test --image_size=300 --detect --segment --ckpt=1 --x4
```

However, I always get the error:
```
2017-09-18 09:55:31.514242: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
         [[Node: save/Assign_266 = Assign[T=DT_FLOAT, _class=["loc:@ssd/Conv/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ssd/Conv/weights, save/RestoreV2_266/_31)]]
2017-09-18 09:55:31.515242: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,64] rhs shape= [3,3,512,64]
```
The input tensor has different shape, could it be a bug or I am doing something wrong?

@DrSleep , did you tried to run the test.py code?

**Comment by fastlater** [comment]
Sorry. I found the answer in one closed issue. However, I hope you can add (whenever you have time) in the Readme how to prepare the dataset and how to use your code to train with our own dataset. I would like to go beyond COCO and VOC and maybe provide feedback on how your code runs using other datasets, for example, blood sample, manufacturing defect, etc.

**Comment by dvornikita** [comment]
Hi,
Actually, the pipeline is able to produce segmentation masks even for a dataset that doesn't have segmentation annotations. When you switch off segmentation you don't run into the error because you don't restore the weights in the segmentation branch of the graph - exactly where the conflict is happening. 
There is a parameter in config.py called --seg_filter_size which is set to 1 by default (you can find it's description there). However, the model we provide was trained with --seg_filter_size=3. To match this just add the flag --seg_filter_size=3 to you run and enjoy segmentations :)
Thank you for noticing this. I'll change the default value to 3 and push that so people can enjoy segmentations too.

**Comment by fastlater** [comment]
Thank you for your response. 
I ran the code perfectly following your advise.
I will continue testing the code and I will notify you if I believe it might interest you to know.

**Comment by dvornikita** [comment]
@fastlater on the datasets side, you need to define a reader that is similar to voc_loader.py or coco_loader.py that provides bounding boxes and segmentation for the encoding pipeline in datasets.py. You may also want to change the evaluation strategy for your dataset in evaluation.py and matching with gt criterias, but the last ones are mostly adjustable from config.py.
I'm thinking about rewriting the data feeding strategy to just queues instead of packed datasets since it was made only to stabilize data-flow in our ecosystem (not sure when I can do it though). Then, the pipeline will become more clear, but the need to create your own loader and evaluation is still there. You may start with this for now.
Don't hesitate to contact me if you have questions on that.

**Comment by fastlater** [comment]
@dvornikita  Thank you again for your response and point me in the right direction. I will do my best.
